#!/bin/sh
#
# NAME
#
#   setlist
#
# DESCRIPTION
#
#   A setlist for the platform build process, describing files to be copied and
#   packages to be installed and uninstalled.
#
# AUTHOR
#
#   Originally written by Michael Spencer.
#   Maintained by the Wren project developers.
#
#
# The Wren project; Copyright 2013-2015 the Wren project developers.
# See the COPYRIGHT file in the top-level directory of this distribution
# for individual attributions.
#
# This file is part of the Wren project. It is subject to the license terms
# in the LICENSE file found in the top-level directory of this distribution.
# No part of the Wren project, including this file, may be copied, modified,
# propagated, or distributed except according to the terms contained in the
# LICENSE file.
#
# This program comes with ABSOLUTELY NO WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# LICENSE file found in the top-level directory of this distribution for
# more details.
#

# Columns denote To / From (destination and source, multi-space separated).
# Use a hyphen (-) as the "from" value to delete the "to" file / directory.
# Common platform run environment variables are allowed.
# Paths should not contain spaces.
SETLIST_COPY="
    $RUN_ENV_PLATFORM_PATH                                          -
    $RUN_ENV_PLATFORM_PATH/COPYRIGHT                                COPYRIGHT
    $RUN_ENV_PLATFORM_PATH/LICENSE                                  LICENSE
    $RUN_ENV_PLATFORM_PATH/bin/save.sh                              copy/bin/save.sh
    $RUN_ENV_PLATFORM_PATH/bin/update-grub.sh                       copy/bin/update-grub.sh
    $RUN_ENV_PLATFORM_PATH/bin/wren                                 copy/bin/wren
    $RUN_ENV_PLATFORM_PATH/etc/boot.conf.example                    copy/etc/boot.conf
    $RUN_ENV_PLATFORM_PATH/etc/device.conf.example                  copy/etc/device.conf
    $RUN_ENV_PLATFORM_PATH/etc/platform.conf.example                copy/etc/platform.conf
    $RUN_ENV_PLATFORM_PATH/grub/grub.cfg.example                    copy/grub/grub.cfg
    $RUN_ENV_PLATFORM_PATH/lib/platform-env                         copy/lib/platform-env
    $RUN_ENV_PLATFORM_PATH/tools/disable-root.sh                    copy/tools/disable-root.sh
    $RUN_ENV_PLATFORM_PATH/tools/enable-root.sh                     copy/tools/enable-root.sh
    $RUN_ENV_PLATFORM_PATH/tools/rename-user.sh                     copy/tools/rename-user.sh
    /etc/apt/preferences.d/no-bootloader                            copy/config/apt/no-bootloader
    /etc/apt/preferences.d/no-misc                                  copy/config/apt/no-misc
    /etc/cron.d/$RUN_ENV_PLATFORM_NAME-increase-active-capacity     copy/config/cron/increase-active-capacity
    /etc/initramfs-tools/hooks/_platform                            copy/initramfs/initramfs-hooks
    /etc/initramfs-tools/modules                                    copy/initramfs/modules
    /etc/initramfs-tools/scripts/init-bottom/_platform              copy/initramfs/initramfs-script
    /etc/initramfs-tools/scripts/platform-env                       copy/lib/platform-env
    /etc/sysctl.d/99-swappiness.conf                                copy/config/sys/99-swappiness.conf
    /etc/udev/rules.d/99-dmapper-hide.rules                         copy/config/udev/99-dmapper-hide.rules
    /usr/src/$RUN_ENV_PLATFORM_NAME-$RUN_ENV_PLATFORM_VERSION       .
"

# Columns denote To / From (destination and source, multi-space separated).
# Paths should not contain spaces.
SETLIST_SYMLINK="
    /usr/sbin/wren  $RUN_ENV_PLATFORM_PATH/bin/wren
"

# A single string of space-separated package names to be passed to
# "apt-get purge" for uninstallation.
SETLIST_UNINSTALL="grub grub-common grub-pc grub2 grub2-common lilo elilo apt-xapian-index oneconf ubuntuone-installer"

# A single string of space-separated package names used to filter files in the
# "install" directory to be passed to "dpkg -i" (in order) for installation.
SETLIST_INSTALL="squashfs-tools btrfs-tools"
